#include <TMP36.h> //INCLUSÃO DE BIBLIOTECA
 
TMP36 myTMP36(A0, 5.0); //DEFINE O PINO ANALÓGICO UTILIZADO PELO SENSOR E
//DEFINE A TENSÃO DE REFERÊNCIA (5V OU 3.3V)
 
void setup() {
  Serial.begin(9600); //INICIALIZA A SERIAL
  //analogReference(EXTERNAL); //REMOVA O COMENTÁRIO DESTA LINHA CASO ESTEJA UTILIZANDO O
  //AREF EM 3.3V
}
 
void loop() {
  float celsius = myTMP36.getTempC(); //VARIÁVEL LOCAL QUE ARMAZENA A TEMPERATURA EM GRAUS CELSIUS
  //OBTIDA ATRAVÉS DA FUNÇÃO myTMP36.getTempC()
 
  Serial.print("Umidade: "); //IMPRIME O TEXTO NO MONITOR SERIAL
  Serial.println(celsius); //IMPRIME NO MONITOR SERIAL A TEMPERATURA MEDIDA
  delay(1000); //INTERVALO DE 1 SEGUNDO
}
